<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>infer • infer</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="infer">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">infer</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.5.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/chisq_test.html">Chi-square Test Example</a>
    </li>
    <li>
      <a href="../articles/two_sample_t.html">Two-Sample t-test Example</a>
    </li>
    <li>
      <a href="../articles/observed_stat_examples.html">Observed Statistic Calculation Examples</a>
    </li>
    <li>
      <a href="../articles/flights_examples.html">Simulation-Based `flights` Examples</a>
    </li>
    <li>
      <a href="../articles/mtcars_examples.html">Examples using `mtcars`</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
<li>
  <a href="../CONTRIBUTING.html">How To Contribute</a>
</li>
<li>
  <a href="../CONDUCT.html">Code of Conduct</a>
</li>
<li>
  <a href="../TO-DO.html">To-Dos</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/tidymodels/infer">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>infer</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/tidymodels/infer/blob/master/vignettes/infer.Rmd"><code>vignettes/infer.Rmd</code></a></small>
      <div class="hidden name"><code>infer.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level3">
<h3 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h3>
<p><code>infer</code> implements an expressive grammar to perform statistical inference that coheres with the <code>tidyverse</code> design framework. Rather than providing methods for specific statistical tests, this package consolidates the principles that are shared among common hypothesis tests into a set of 4 main verbs (functions), supplemented with many utilities to visualize and extract value from their outputs.</p>
<p>Regardless of which hypothesis test we’re using, we’re still asking the same kind of question: is the effect/difference in our observed data real, or due to chance? To answer this question, we start by assuming that the observed data came from some world where “nothing is going on” (i.e. the observed effect was simply due to random chance), and call this assumption our <em>null hypothesis</em>. (In reality, we might not believe in the null hypothesis at all—the null hypothesis is in opposition to the <em>alternate hypothesis</em>, which supposes that the effect present in the observed data is actually due to the fact that “something is going on.”) We then calculate a <em>test statistic</em> from our data that describes the observed effect. We can use this test statistic to calculate a <em>p-value</em>, giving the probability that our observed data could come about if the null hypothesis was true. If this probability is below some pre-defined <em>significance level</em> <span class="math inline">\(\alpha\)</span>, then we can reject our null hypothesis.</p>
<p>The workflow of this package is designed around this idea. Starting out with some dataset,</p>
<ul>
<li>
<code><a href="../reference/specify.html">specify()</a></code> allows you to specify the variable, or relationship between variables, that you’re interested in.</li>
<li>
<code><a href="../reference/hypothesize.html">hypothesize()</a></code> allows you to declare the null hypothesis.</li>
<li>
<code><a href="../reference/generate.html">generate()</a></code> allows you to generate data reflecting the null hypothesis.</li>
<li>
<code><a href="../reference/calculate.html">calculate()</a></code> allows you to calculate a distribution of statistics from the generated data to form the null distribution.</li>
</ul>
<p>Throughout this vignette, we make use of <code>gss</code>, a dataset supplied by <code>infer</code> containing a sample of 3000 observations sampled from the <em>General Social Survey</em>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="co"># load in the dataset</span></a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(gss)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"></a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="co"># take a look at its structure</span></a>
<a class="sourceLine" id="cb1-5" data-line-number="5"><span class="kw"><a href="https://rdrr.io/r/utils/str.html">str</a></span>(gss)</a></code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    3000 obs. of  11 variables:
##  $ year   : num  2008 2006 1985 1987 2006 ...
##   ..- attr(*, "label")= chr "gss year for this respondent "
##   ..- attr(*, "format.stata")= chr "%8.0g"
##  $ age    : num  37 29 58 40 39 37 53 41 55 47 ...
##  $ sex    : Factor w/ 2 levels "male","female": 1 2 1 1 2 1 2 1 1 1 ...
##  $ college: Factor w/ 2 levels "no degree","degree": 1 1 2 2 1 1 1 1 1 1 ...
##  $ partyid: Factor w/ 5 levels "dem","ind","rep",..: 1 1 2 3 1 1 1 3 2 3 ...
##  $ hompop : num  4 3 3 5 5 5 4 1 5 4 ...
##  $ hours  : num  50 NA 60 84 40 50 NA 60 NA 40 ...
##  $ income : Ord.factor w/ 12 levels "lt $1000"&lt;"$1000 to 2999"&lt;..: 12 1 12 12 6 12 11 12 NA 12 ...
##  $ class  : Factor w/ 6 levels "lower class",..: 2 3 3 3 NA 2 2 2 3 2 ...
##  $ finrela: Factor w/ 6 levels "far below average",..: 2 2 5 1 NA 3 NA 3 3 3 ...
##  $ weight : num  0.875 0.43 1.554 1.01 0.859 ...</code></pre>
<p>Each row is an individual survey response, containing some basic demographic information on the respondent as well as some additional variables. See <code><a href="../reference/gss.html">?gss</a></code> for more information on the variables included and their source. Note that this data (and our examples on it) are for demonstration purposes only, and will not provide accurate estimates unless weighted properly. For these examples, let’s suppose that this dataset is a representative sample of a population we want to learn about - American adults.</p>
</div>
<div id="specify-specifying-response-and-explanatory-variables" class="section level3">
<h3 class="hasAnchor">
<a href="#specify-specifying-response-and-explanatory-variables" class="anchor"></a><code>specify()</code>: Specifying Response (and Explanatory) Variables</h3>
<p>The <code>specify</code> function can be used to specify which of the variables in the dataset you’re interested in. If you’re only interested in, say, the <code>age</code> of the respondents, you might write:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> age)</a></code></pre></div>
<pre><code>## Response: age (numeric)
## # A tibble: 2,988 x 1
##      age
##    &lt;dbl&gt;
##  1    37
##  2    29
##  3    58
##  4    40
##  5    39
##  6    37
##  7    53
##  8    41
##  9    55
## 10    47
## # … with 2,978 more rows</code></pre>
<p>On the front-end, the output of <code>specify</code> just looks like it selects off the columns in the dataframe that you’ve specified. Checking the class of this object, though:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> age) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb5-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://rdrr.io/r/base/class.html">class</a></span>()</a></code></pre></div>
<pre><code>## [1] "infer"      "tbl_df"     "tbl"        "data.frame"</code></pre>
<p>We can see that the <code>infer</code> class has been appended on top of the dataframe classes–this new class stores some extra metadata.</p>
<p>If you’re interested in two variables–<code>age</code> and <code>partyid</code>, for example–you can <code>specify</code> their relationship in one of two (equivalent) ways:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="co"># with the named arguments</span></a>
<a class="sourceLine" id="cb7-2" data-line-number="2">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb7-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(age <span class="op">~</span><span class="st"> </span>partyid)</a></code></pre></div>
<pre><code>## Response: age (numeric)
## Explanatory: partyid (factor)
## # A tibble: 2,963 x 2
##      age partyid
##    &lt;dbl&gt; &lt;fct&gt;  
##  1    37 dem    
##  2    29 dem    
##  3    58 ind    
##  4    40 rep    
##  5    39 dem    
##  6    37 dem    
##  7    53 dem    
##  8    41 rep    
##  9    55 ind    
## 10    47 rep    
## # … with 2,953 more rows</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="co"># as a formula</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb9-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> age, <span class="dt">explanatory =</span> partyid)</a></code></pre></div>
<pre><code>## Response: age (numeric)
## Explanatory: partyid (factor)
## # A tibble: 2,963 x 2
##      age partyid
##    &lt;dbl&gt; &lt;fct&gt;  
##  1    37 dem    
##  2    29 dem    
##  3    58 ind    
##  4    40 rep    
##  5    39 dem    
##  6    37 dem    
##  7    53 dem    
##  8    41 rep    
##  9    55 ind    
## 10    47 rep    
## # … with 2,953 more rows</code></pre>
<p>If you’re doing inference on one proportion or a difference in proportions, you will need to use the <code>success</code> argument to specify which level of your <code>response</code> variable is a success. For instance, if you’re interested in the proportion of the population with a college degree, you might use the following code:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="co"># specifying for inference on proportions</span></a>
<a class="sourceLine" id="cb11-2" data-line-number="2">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb11-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> college, <span class="dt">success =</span> <span class="st">"degree"</span>)</a></code></pre></div>
<pre><code>## Response: college (factor)
## # A tibble: 2,990 x 1
##    college  
##    &lt;fct&gt;    
##  1 no degree
##  2 no degree
##  3 degree   
##  4 degree   
##  5 no degree
##  6 no degree
##  7 no degree
##  8 no degree
##  9 no degree
## 10 no degree
## # … with 2,980 more rows</code></pre>
</div>
<div id="hypothesize-declaring-the-null-hypothesis" class="section level3">
<h3 class="hasAnchor">
<a href="#hypothesize-declaring-the-null-hypothesis" class="anchor"></a><code>hypothesize()</code>: Declaring the Null Hypothesis</h3>
<p>The next step in the <code>infer</code> pipeline is often to declare a null hypothesis using <code><a href="../reference/hypothesize.html">hypothesize()</a></code>. The first step is to supply one of “independence” or “point” to the <code>null</code> argument. If your null hypothesis assumes independence between two variables, then this is all you need to supply to <code><a href="../reference/hypothesize.html">hypothesize()</a></code>:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(college <span class="op">~</span><span class="st"> </span>partyid, <span class="dt">success =</span> <span class="st">"degree"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb13-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/hypothesize.html">hypothesize</a></span>(<span class="dt">null =</span> <span class="st">"independence"</span>)</a></code></pre></div>
<pre><code>## Response: college (factor)
## Explanatory: partyid (factor)
## Null Hypothesis: independence
## # A tibble: 2,967 x 2
##    college   partyid
##    &lt;fct&gt;     &lt;fct&gt;  
##  1 no degree dem    
##  2 no degree dem    
##  3 degree    ind    
##  4 degree    rep    
##  5 no degree dem    
##  6 no degree dem    
##  7 no degree dem    
##  8 no degree rep    
##  9 no degree ind    
## 10 no degree rep    
## # … with 2,957 more rows</code></pre>
<p>If you’re doing inference on a point estimate, you will also need to provide one of <code>p</code> (the true proportion of successes, between 0 and 1), <code>mu</code> (the true mean), <code>med</code> (the true median), or <code>sigma</code> (the true standard deviation). For instance, if the null hypothesis is that the mean number of hours worked per week in our population is 40, we would write:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> hours) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb15-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/hypothesize.html">hypothesize</a></span>(<span class="dt">null =</span> <span class="st">"point"</span>, <span class="dt">mu =</span> <span class="dv">40</span>)</a></code></pre></div>
<pre><code>## Response: hours (numeric)
## Null Hypothesis: point
## # A tibble: 1,756 x 1
##    hours
##    &lt;dbl&gt;
##  1    50
##  2    60
##  3    84
##  4    40
##  5    50
##  6    60
##  7    40
##  8    20
##  9    40
## 10    40
## # … with 1,746 more rows</code></pre>
<p>Again, from the front-end, the dataframe outputted from <code><a href="../reference/hypothesize.html">hypothesize()</a></code> looks almost exactly the same as it did when it came out of <code><a href="../reference/specify.html">specify()</a></code>, but <code>infer</code> now “knows” your null hypothesis.</p>
</div>
<div id="generate-generating-the-null-distribution" class="section level3">
<h3 class="hasAnchor">
<a href="#generate-generating-the-null-distribution" class="anchor"></a><code>generate()</code>: Generating the Null Distribution</h3>
<p>Once we’ve asserted our null hypothesis using <code><a href="../reference/hypothesize.html">hypothesize()</a></code>, we can construct a null distribution based on this hypothesis. We can do this using one of several methods, supplied in the <code>type</code> argument:</p>
<ul>
<li>
<code>bootstrap</code>: A bootstrap sample will be drawn for each replicate, where a sample of size equal to the input sample size is drawn (with replacement) from the input sample data.<br>
</li>
<li>
<code>permute</code>: For each replicate, each input value will be randomly reassigned (without replacement) to a new output value in the sample.<br>
</li>
<li>
<code>simulate</code>: A value will be sampled from a theoretical distribution with parameters specified in <code><a href="../reference/hypothesize.html">hypothesize()</a></code> for each replicate. (This option is currently only applicable for testing point estimates.)</li>
</ul>
<p>Continuing on with our example above, about the average number of hours worked a week, we might write:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> hours) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/hypothesize.html">hypothesize</a></span>(<span class="dt">null =</span> <span class="st">"point"</span>, <span class="dt">mu =</span> <span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb17-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/generate.html">generate</a></span>(<span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">type =</span> <span class="st">"bootstrap"</span>)</a></code></pre></div>
<pre><code>## Response: hours (numeric)
## Null Hypothesis: point
## # A tibble: 1,756,000 x 2
## # Groups:   replicate [1,000]
##    replicate hours
##        &lt;int&gt; &lt;dbl&gt;
##  1         1 39.2 
##  2         1 39.2 
##  3         1 39.2 
##  4         1  2.23
##  5         1 19.2 
##  6         1 71.2 
##  7         1 34.2 
##  8         1 39.2 
##  9         1 39.2 
## 10         1 45.2 
## # … with 1,755,990 more rows</code></pre>
<p>In the above example, we take 1000 bootstrap samples to form our null distribution.</p>
<p>To generate a null distribution for the independence of two variables, we could also randomly reshuffle the pairings of explanatory and response variables to break any existing association. For instance, to generate 1000 replicates that can be used to create a null distribution under the assumption that political party affiliation is not affected by age:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(partyid <span class="op">~</span><span class="st"> </span>age) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb19-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/hypothesize.html">hypothesize</a></span>(<span class="dt">null =</span> <span class="st">"independence"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb19-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/generate.html">generate</a></span>(<span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">type =</span> <span class="st">"permute"</span>)</a></code></pre></div>
<pre><code>## Response: partyid (factor)
## Explanatory: age (numeric)
## Null Hypothesis: independence
## # A tibble: 2,963,000 x 3
## # Groups:   replicate [1,000]
##    partyid   age replicate
##    &lt;fct&gt;   &lt;dbl&gt;     &lt;int&gt;
##  1 ind        37         1
##  2 ind        29         1
##  3 dem        58         1
##  4 dem        40         1
##  5 ind        39         1
##  6 dem        37         1
##  7 dem        53         1
##  8 ind        41         1
##  9 ind        55         1
## 10 ind        47         1
## # … with 2,962,990 more rows</code></pre>
</div>
<div id="calculate-calculating-summary-statistics" class="section level3">
<h3 class="hasAnchor">
<a href="#calculate-calculating-summary-statistics" class="anchor"></a><code>calculate()</code>: Calculating Summary Statistics</h3>
<p>Depending on whether you’re carrying out computation-based inference or theory-based inference, you will either supply <code><a href="../reference/calculate.html">calculate()</a></code> with the output of <code><a href="../reference/generate.html">generate()</a></code> or <code>hypothesize</code>, respectively. The function, for one, takes in a <code>stat</code> argument, which is currently one of “mean”, “median”, “sum”, “sd”, “prop”, “count”, “diff in means”, “diff in medians”, “diff in props”, “Chisq”, “F”, “t”, “z”, “slope”, or “correlation”. For example, continuing our example above to calculate the null distribution of mean hours worked per week:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb21-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> hours) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb21-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/hypothesize.html">hypothesize</a></span>(<span class="dt">null =</span> <span class="st">"point"</span>, <span class="dt">mu =</span> <span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb21-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/generate.html">generate</a></span>(<span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">type =</span> <span class="st">"bootstrap"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb21-5" data-line-number="5"><span class="st">  </span><span class="kw"><a href="../reference/calculate.html">calculate</a></span>(<span class="dt">stat =</span> <span class="st">"mean"</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 2
##    replicate  stat
##        &lt;int&gt; &lt;dbl&gt;
##  1         1  39.9
##  2         2  40.5
##  3         3  40.2
##  4         4  40.1
##  5         5  39.8
##  6         6  40.2
##  7         7  39.3
##  8         8  39.8
##  9         9  40.2
## 10        10  39.9
## # … with 990 more rows</code></pre>
<p>The output of <code><a href="../reference/calculate.html">calculate()</a></code> here shows us the sample statistic (in this case, the mean) for each of our 1000 replicates. If you’re carrying out inference on differences in means, medians, or proportions, or t and z statistics, you will need to supply an <code>order</code> argument, giving the order in which the explanatory variables should be subtracted. For instance, to find the difference in mean age of those that have a college degree and those that don’t, we might write:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(age <span class="op">~</span><span class="st"> </span>college) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/hypothesize.html">hypothesize</a></span>(<span class="dt">null =</span> <span class="st">"independence"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/generate.html">generate</a></span>(<span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">type =</span> <span class="st">"permute"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="st">  </span><span class="kw"><a href="../reference/calculate.html">calculate</a></span>(<span class="st">"diff in means"</span>, <span class="dt">order =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"degree"</span>, <span class="st">"no degree"</span>))</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 2
##    replicate   stat
##        &lt;int&gt;  &lt;dbl&gt;
##  1         1  0.196
##  2         2 -0.448
##  3         3 -0.890
##  4         4  1.04 
##  5         5  0.267
##  6         6  0.146
##  7         7 -0.343
##  8         8  0.984
##  9         9  0.653
## 10        10  0.240
## # … with 990 more rows</code></pre>
</div>
<div id="other-utilities-in-infer" class="section level3">
<h3 class="hasAnchor">
<a href="#other-utilities-in-infer" class="anchor"></a>Other Utilities in <code>infer</code>
</h3>
<p><code>infer</code> also offers several utilities to extract the meaning out of summary statistics and null distributions—the package provides functions to visualize where a statistic is relative to a distribution (with <code><a href="../reference/visualize.html">visualize()</a></code>), calculate p-values (with <code><a href="../reference/get_p_value.html">get_p_value()</a></code>), and calculate confidence intervals (with <code><a href="../reference/get_confidence_interval.html">get_confidence_interval()</a></code>).</p>
<p>To illustrate, we’ll go back to the example of determining whether the mean number of hours worked per week is 40 hours.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="co"># find the point estimate</span></a>
<a class="sourceLine" id="cb25-2" data-line-number="2">point_estimate &lt;-<span class="st"> </span>gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb25-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> hours) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb25-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/calculate.html">calculate</a></span>(<span class="dt">stat =</span> <span class="st">"mean"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb25-5" data-line-number="5"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span>()</a></code></pre></div>
<pre><code>## Warning: Removed 1244 rows containing missing values.</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="co"># generate a null distribution</span></a>
<a class="sourceLine" id="cb27-2" data-line-number="2">null_dist &lt;-<span class="st"> </span>gss <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/specify.html">specify</a></span>(<span class="dt">response =</span> hours) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/hypothesize.html">hypothesize</a></span>(<span class="dt">null =</span> <span class="st">"point"</span>, <span class="dt">mu =</span> <span class="dv">40</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-5" data-line-number="5"><span class="st">  </span><span class="kw"><a href="../reference/generate.html">generate</a></span>(<span class="dt">reps =</span> <span class="dv">10000</span>, <span class="dt">type =</span> <span class="st">"bootstrap"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-6" data-line-number="6"><span class="st">  </span><span class="kw"><a href="../reference/calculate.html">calculate</a></span>(<span class="dt">stat =</span> <span class="st">"mean"</span>)</a></code></pre></div>
<pre><code>## Warning: Removed 1244 rows containing missing values.</code></pre>
<p>(Notice the warning: <code>Removed 1244 rows containing missing values.</code> This would be worth noting if you were actually carrying out this hypothesis test.)</p>
<p>Our point estimate 40.7722 seems <em>pretty</em> close to 40, but a little bit different. We might wonder if this difference is just due to random chance, or if the mean number of hours worked per week in the population really isn’t 40.</p>
<p>We could initially just visualize the null distribution.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">null_dist <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/visualize.html">visualize</a></span>()</a></code></pre></div>
<p><img src="infer_files/figure-html/visualize-1.png" width="576"></p>
<p>Where does our sample’s observed statistic lie on this distribution? We can use the <code>obs_stat</code> argument to specify this.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1">null_dist <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb30-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/visualize.html">visualize</a></span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb30-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/shade_p_value.html">shade_p_value</a></span>(<span class="dt">obs_stat =</span> point_estimate, <span class="dt">direction =</span> <span class="st">"two_sided"</span>)</a></code></pre></div>
<p><img src="infer_files/figure-html/visualize2-1.png" width="576"></p>
<p>Notice that <code>infer</code> has also shaded the regions of the null distribution that are as (or more) extreme than our observed statistic. (Also, note that we now use the <code><a href="https://rdrr.io/r/base/Arithmetic.html">+</a></code> operator to apply the <code>shade_p_value</code> function. This is because <code>visualize</code> outputs a plot object from <code>ggplot2</code> instead of a data frame, and the <code><a href="https://rdrr.io/r/base/Arithmetic.html">+</a></code> operator is needed to add the p-value layer to the plot object.) The red bar looks like it’s pretty far out on the right tail of the null distribution, so observing a sample mean of 40.7722 hours would be pretty unlikely if the mean was actually 40 hours. How unlikely, though?</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="co"># get a two-tailed p-value</span></a>
<a class="sourceLine" id="cb31-2" data-line-number="2">p_value &lt;-<span class="st"> </span>null_dist <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb31-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="../reference/get_p_value.html">get_p_value</a></span>(<span class="dt">obs_stat =</span> point_estimate, <span class="dt">direction =</span> <span class="st">"two_sided"</span>)</a>
<a class="sourceLine" id="cb31-4" data-line-number="4"></a>
<a class="sourceLine" id="cb31-5" data-line-number="5">p_value</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1  0.0196</code></pre>
<p>It looks like the p-value is 0.0196, which is pretty small—if the true mean number of hours worked per week was actually 40, the probability of our sample mean being this far (0.7722 hours) from 40 would be 0.0196. This may or may not be statistically significantly different, depending on the significance level <span class="math inline">\(\alpha\)</span> you decided on <em>before</em> you ran this analysis. If you had set <span class="math inline">\(\alpha = .05\)</span>, then this difference would be statistically significant, but if you had set <span class="math inline">\(\alpha = .01\)</span>, then it would not be.</p>
<p>To get a confidence interval around our estimate, we can write:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="co"># start with the null distribution</span></a>
<a class="sourceLine" id="cb33-2" data-line-number="2">null_dist <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb33-3" data-line-number="3"><span class="st">  </span><span class="co"># calculate the confidence interval around the point estimate</span></a>
<a class="sourceLine" id="cb33-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/get_confidence_interval.html">get_confidence_interval</a></span>(<span class="dt">point_estimate =</span> point_estimate,</a>
<a class="sourceLine" id="cb33-5" data-line-number="5">                          <span class="co"># at the 95% confidence level</span></a>
<a class="sourceLine" id="cb33-6" data-line-number="6">                          <span class="dt">level =</span> <span class="fl">.95</span>,</a>
<a class="sourceLine" id="cb33-7" data-line-number="7">                          <span class="co"># using the standard error</span></a>
<a class="sourceLine" id="cb33-8" data-line-number="8">                          <span class="dt">type =</span> <span class="st">"se"</span>)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   lower upper
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  40.1  41.4</code></pre>
<p>As you can see, 40 hours per week is not contained in this interval, which aligns with our previous conclusion that this finding is significant at the confidence level <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>This vignette covers most all of the key functionality of infer. See <code><a href="https://rdrr.io/r/utils/help.html">help(package = "infer")</a></code> for a full list of functions and vignettes.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Andrew Bray, Chester Ismay, Evgeni Chasnovski, Ben Baumer, Mine Cetinkaya-Rundel.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: '33338960d0dcb55ff924a40c2f749a0d',
    indexName: 'infer',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
